on:
  push

jobs:
  test-visio-install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Visio
        uses: ./

      - name: Install officetopdf
        run: choco install office-to-pdf -y

      - name: Download sample drawing and export to PDF
        shell: pwsh
        run: |
          ls
          echo "Downloading sample Visio drawing"
          Invoke-WebRequest -Uri "https://omextemplates.content.office.net/support/templates/en-us/tf16403437.vsdx" -OutFile "drawing.vsdx" 
          ls
          echo "Converting to pdf"
          officetopdf.exe .\drawing.vsdx .\out.pdf
          ls

      #- name: Verify Visio Installation
      #  shell: pwsh
      #  run: |
      #    $visio = New-Object -ComObject Visio.Application
      #    $visio.Visible = $false
      #    if ($visio -ne $null) {
      #        Write-Host "Visio installed successfully."
      #        $visio.Quit()
      #    } else {
      #        throw "Visio installation failed."
      #    }